name: CI-homework

on:
  push:
    tags:
      - rc-*

jobs:
  tests:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
          npm run lint
          npm run test
  dockerize:

    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/infra
          tags: |
            type=ref,event=tag
      - name: push to dockerhub
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  report_to_tracker:
    name: Send report to tracker
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d/%m/%Y')"
      - name: Get description
        id: description
        run: echo "::set-output name=log::$(git log --pretty=format:"%h %cn %s" ${{ github.ref_name }})"
      - name: update ticket
        run: |
          curl --location --request PATCH 'https://api.tracker.yandex.net/v2/issues/HOMEWORKSHRI-154' \
          --header 'X-Org-ID: ${{ secrets.ORG_ID }}' \
          --header 'Authorization: OAuth ${{ secrets.TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"summary": "Релиз ${{ github.ref_name }} - ${{ steps.date.outputs.date }}", "description": "Ответственный за релиз: ${{ github.event.pusher.name }} \n коммиты, попавшие в релиз: \n ${{ steps.description.outputs.log }}"}'