name: CI-homework

on:
  push:
    tags:
      - rc-*

jobs:
  tests:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: |
          npm run lint
          npm run test

      - name: build
        run: npm run build

  build_and_push_to_docker_hub:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/infra
          tags: |
            type=ref,event=tag

      - name: push to dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
